"""2D Axisymmetric Magnetic Field Solver for Planar DC Magnetrons.

Calculates the spatial magnetic field distribution B(r, z) generated by
concentric permanent magnet assemblies (central cylinder N-pole + outer annular ring S-pole):
1. Exact magnetic field components B_r(r, z), B_z(r, z), and |B(r, z)|
2. Magnetic vector potential A_theta(r, z) and flux function psi(r, z) = r * A_theta
3. Racetrack null-point where B_z(r, z=0) = 0 (purely parallel B-field for E x B drift)
4. Electron cyclotron frequency omega_ce(r, z) and Hall parameter beta_e(r, z)
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np
from scipy.special import ellipe, ellipk

# Fundamental physical constants
_MU_0: float = 4.0 * math.pi * 1e-7  # Vacuum permeability in T*m/A (H/m)
_E_CHARGE_C: float = 1.602176634e-19  # Elementary charge in C
_M_E_KG: float = 9.1093837e-31  # Electron mass in kg
_K_B_J_K: float = 1.380649e-23  # Boltzmann constant in J/K


@dataclass(frozen=True)
class MagnetronGeometry:
    """Dimensions and magnetic parameters for a planar circular magnetron assembly."""

    target_radius_m: float = 0.050        # 50 mm (2-inch disk)
    target_thickness_m: float = 0.006     # 6 mm backing plate + target thickness
    central_magnet_radius_m: float = 0.010 # 10 mm central cylindrical magnet
    central_magnet_height_m: float = 0.015 # 15 mm height
    outer_ring_inner_radius_m: float = 0.022 # 22 mm inner radius of ring
    outer_ring_outer_radius_m: float = 0.034 # 34 mm outer radius of ring
    outer_ring_height_m: float = 0.015       # 15 mm height
    remanence_br_tesla: float = 0.35        # Remanence of NdFeB / SmCo magnets (~0.35 T)


@dataclass
class MagneticField2D:
    """2D Spatial Magnetic Field Solution on cylindrical grid (r, z)."""

    r_grid_m: np.ndarray      # Radial coordinates (m), shape: (Nr,)
    z_grid_m: np.ndarray      # Axial coordinates from target surface z=0 upward (m), shape: (Nz,)
    B_r: np.ndarray           # Radial magnetic field (T), shape: (Nz, Nr)
    B_z: np.ndarray           # Axial magnetic field (T), shape: (Nz, Nr)
    B_mag: np.ndarray         # Magnetic field magnitude |B| (T), shape: (Nz, Nr)
    psi_flux: np.ndarray      # Magnetic flux function r * A_theta (T*m^2), shape: (Nz, Nr)
    racetrack_radius_m: float # Computed radial location on target where B_z = 0
    b_parallel_peak_tesla: float # Peak radial field at the racetrack center (T)
    trap_thickness_m: float   # Vertical extent of magnetic trap (where |B| > 0.01 T)

    def cyclotron_frequency(self) -> np.ndarray:
        """Calculate electron cyclotron frequency omega_ce = e * |B| / m_e [rad/s]."""
        return (_E_CHARGE_C * self.B_mag) / _M_E_KG

    def hall_parameter(self, pressure_mtorr: float, Te_ev: float = 3.0) -> np.ndarray:
        """Calculate electron Hall parameter beta_e = omega_ce / nu_en.

        Where beta_e >> 1 indicates magnetized electrons trapped in E x B drift rings.
        """
        # Argon neutral gas density: n_g = P / (k_B * T_gas)
        p_pa = pressure_mtorr * 0.133322
        t_gas_k = 300.0
        n_g = p_pa / (_K_B_J_K * t_gas_k)

        # Electron thermal speed v_th = sqrt(8 * e * Te / (pi * m_e))
        v_th_e = math.sqrt((8.0 * _E_CHARGE_C * Te_ev) / (math.pi * _M_E_KG))

        # Electron-neutral momentum transfer cross section in Ar (Ramsauer-Townsend effect ~ 4e-20 m^2)
        sigma_en = 4.0e-20
        nu_en = n_g * sigma_en * v_th_e  # Collision frequency (s^-1)

        omega_ce = self.cyclotron_frequency()
        return omega_ce / (nu_en + 1e-12)


def _single_loop_b_field(
    r: np.ndarray,
    z: np.ndarray,
    loop_radius: float,
    loop_z: float,
    current: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Analytical magnetic field of a single circular current loop in (r, z).

    Uses complete elliptic integrals K(k^2) and E(k^2).
    """
    a = loop_radius
    dz = z - loop_z

    # Distance denominator terms
    d_plus_sq = (a + r) ** 2 + dz ** 2
    d_minus_sq = (a - r) ** 2 + dz ** 2

    # Prevent division by zero directly on loop wire
    d_minus_sq = np.maximum(d_minus_sq, 1e-12)
    d_plus_sq = np.maximum(d_plus_sq, 1e-12)

    # Elliptic modulus squared k^2 = 4 a r / ((a + r)^2 + dz^2)
    k_sq = (4.0 * a * r) / d_plus_sq
    k_sq = np.clip(k_sq, 0.0, 0.9999999)

    K = ellipk(k_sq)
    E = ellipe(k_sq)

    prefactor = (_MU_0 * current) / (2.0 * math.pi * np.sqrt(d_plus_sq))

    # On-axis (r -> 0) limits
    r_safe = np.where(r > 1e-6, r, 1e-6)

    # Radial component B_r = prefactor * (dz / r) * [ -K + (a^2 + r^2 + dz^2)/( (a-r)^2 + dz^2 ) * E ]
    b_r = prefactor * (dz / r_safe) * (-K + ((a ** 2 + r ** 2 + dz ** 2) / d_minus_sq) * E)
    b_r = np.where(r <= 1e-6, 0.0, b_r)  # Zero on axis by symmetry

    # Axial component B_z = prefactor * [ K + (a^2 - r^2 - dz^2)/( (a-r)^2 + dz^2 ) * E ]
    b_z = prefactor * (K + ((a ** 2 - r ** 2 - dz ** 2) / d_minus_sq) * E)

    # Vector potential component A_theta
    # A_theta = (mu_0 * I / (pi * k)) * sqrt(a/r) * [(1 - k^2/2) K - E]
    k_val = np.sqrt(k_sq)
    k_safe = np.maximum(k_val, 1e-6)
    a_theta = ((_MU_0 * current) / (math.pi * k_safe)) * np.sqrt(a / r_safe) * ((1.0 - 0.5 * k_sq) * K - E)
    a_theta = np.where(r <= 1e-6, 0.0, a_theta)

    return b_r, b_z, a_theta


def compute_magnetron_magnetic_field(
    geom: Optional[MagnetronGeometry] = None,
    grid_r_points: int = 80,
    grid_z_points: int = 60,
    z_max_m: float = 0.050,  # 50 mm above target
) -> MagneticField2D:
    """Compute full 2D axisymmetric magnetic field for planar DC magnetron."""
    g = geom or MagnetronGeometry()

    r_vec = np.linspace(0.0, g.target_radius_m, grid_r_points)
    z_vec = np.linspace(0.0, z_max_m, grid_z_points)
    R, Z = np.meshgrid(r_vec, z_vec)

    # Magnet positions are located below the target surface (z < 0)
    # Target top surface is at z = 0.
    # Top of magnets is at z = -target_thickness_m.
    # Bottom of magnets is at z = -(target_thickness_m + height_m).
    z_mag_top = -g.target_thickness_m
    z_mag_bot = -(g.target_thickness_m + g.central_magnet_height_m)

    # Effective surface current: M_z = Br / mu_0 [A/m]
    m_mag = g.remanence_br_tesla / _MU_0

    b_r_total = np.zeros_like(R)
    b_z_total = np.zeros_like(Z)
    a_theta_total = np.zeros_like(R)

    # Number of discrete current loops along vertical thickness
    n_loops = 12
    z_loops = np.linspace(z_mag_bot, z_mag_top, n_loops)
    dz_loop = (z_mag_top - z_mag_bot) / n_loops

    # 1. Central cylindrical magnet (North pole facing target: positive M_z)
    # Modeled as a surface current loop of radius central_magnet_radius_m
    i_central = m_mag * dz_loop
    for zl in z_loops:
        br, bz, ath = _single_loop_b_field(R, Z, g.central_magnet_radius_m, zl, i_central)
        b_r_total += br
        b_z_total += bz
        a_theta_total += ath

    # 2. Outer ring magnet (South pole facing target: negative M_z)
    # Modeled as two concentric current sheets:
    # Inner radius has negative current; outer radius has positive current
    for zl in z_loops:
        # Inner surface of ring magnet (+ current since outward normal points toward center)
        br_in, bz_in, ath_in = _single_loop_b_field(
            R, Z, g.outer_ring_inner_radius_m, zl, i_central
        )
        b_r_total += br_in
        b_z_total += bz_in
        a_theta_total += ath_in

        # Outer surface of ring magnet (- current)
        br_out, bz_out, ath_out = _single_loop_b_field(
            R, Z, g.outer_ring_outer_radius_m, zl, -i_central
        )
        b_r_total += br_out
        b_z_total += bz_out
        a_theta_total += ath_out

    b_mag = np.sqrt(b_r_total ** 2 + b_z_total ** 2)
    psi = R * a_theta_total

    # 3. Find the exact racetrack location where B_z = 0 at the target surface (z = 0, index 0)
    bz_surface = b_z_total[0, :]
    # Locate zero crossing where B_z changes sign from positive (central N) to negative (outer S)
    zero_crossings = np.where(np.diff(np.sign(bz_surface)))[0]

    if len(zero_crossings) > 0:
        idx = zero_crossings[0]
        # Linear interpolation for sub-grid precision
        r1, r2 = r_vec[idx], r_vec[idx + 1]
        bz1, bz2 = bz_surface[idx], bz_surface[idx + 1]
        r_race = r1 - bz1 * (r2 - r1) / (bz2 - bz1)
    else:
        # Fallback to standard 0.5 ratio
        r_race = 0.5 * g.target_radius_m

    # Peak parallel field B_r at the racetrack center (z = 0)
    idx_race = int(np.argmin(np.abs(r_vec - r_race)))
    b_parallel_peak = float(np.abs(b_r_total[0, idx_race]))

    # Vertical trap thickness: interpolated height above the racetrack where
    # |B| falls to 1/e of its surface value. Linear interpolation keeps the
    # metric independent of the axial grid resolution (a pure index lookup
    # quantizes it to dz and makes downstream closures grid-sensitive).
    b_vertical_race = b_mag[:, idx_race]
    b_surface = float(b_vertical_race[0])
    trap_threshold = b_surface * math.exp(-1.0)
    trap_thickness = float(z_vec[-1])
    if b_surface > 0.0:
        for iz in range(1, b_vertical_race.size):
            if b_vertical_race[iz] <= trap_threshold:
                b0, b1 = float(b_vertical_race[iz - 1]), float(b_vertical_race[iz])
                z0, z1 = float(z_vec[iz - 1]), float(z_vec[iz])
                frac = (b0 - trap_threshold) / (b0 - b1) if b0 != b1 else 0.0
                trap_thickness = z0 + frac * (z1 - z0)
                break

    return MagneticField2D(
        r_grid_m=r_vec,
        z_grid_m=z_vec,
        B_r=b_r_total,
        B_z=b_z_total,
        B_mag=b_mag,
        psi_flux=psi,
        racetrack_radius_m=float(r_race),
        b_parallel_peak_tesla=b_parallel_peak,
        trap_thickness_m=trap_thickness,
    )
